import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Language descriptor model.
class LanguageOption {
  final String code;
  final String englishName;
  final String nativeName;
  final bool isRtl;

  const LanguageOption({
    required this.code,
    required this.englishName,
    required this.nativeName,
    this.isRtl = false,
  });
}

/// Global Localization & Multi-Language Engine for Tally.
class LanguageService {
  LanguageService._();

  static const String _prefLanguageKey = 'tally_selected_language';

  /// Supported languages across international locales.
  static const List<LanguageOption> supportedLanguages = [
    LanguageOption(code: 'en', englishName: 'English', nativeName: 'English'),
    LanguageOption(code: 'es', englishName: 'Spanish', nativeName: 'Español'),
    LanguageOption(code: 'fr', englishName: 'French', nativeName: 'Français'),
    LanguageOption(code: 'de', englishName: 'German', nativeName: 'Deutsch'),
    LanguageOption(code: 'ur', englishName: 'Urdu', nativeName: 'اردو', isRtl: true),
    LanguageOption(code: 'ar', englishName: 'Arabic', nativeName: 'العربية', isRtl: true),
    LanguageOption(code: 'hi', englishName: 'Hindi', nativeName: 'हिन्दी'),
  ];

  /// Reactive notifier for the currently selected language code.
  static final ValueNotifier<String> currentLanguageNotifier = ValueNotifier<String>('en');

  /// Indicates if the active language is right-to-left (RTL).
  static bool get isRtl {
    final lang = currentLanguageNotifier.value;
    return lang == 'ur' || lang == 'ar';
  }

  /// Initializes the saved language from persistent storage.
  static Future<void> init() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedLang = prefs.getString(_prefLanguageKey);
      if (savedLang != null && supportedLanguages.any((l) => l.code == savedLang)) {
        currentLanguageNotifier.value = savedLang;
      }
    } catch (e) {
      debugPrint('LanguageService.init notice: $e');
    }
  }

  /// Updates and persists the current language.
  static Future<void> setLanguage(String code) async {
    if (!supportedLanguages.any((l) => l.code == code)) return;
    currentLanguageNotifier.value = code;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_prefLanguageKey, code);
    } catch (e) {
      debugPrint('LanguageService.setLanguage notice: $e');
    }
  }

  /// Translates a given key with fallback to English, then to the key itself.
  static String tr(String key) {
    final lang = currentLanguageNotifier.value;
    final dict = _translations[lang];
    if (dict != null && dict.containsKey(key)) {
      return dict[key]!;
    }
    // Fallback to English
    final enDict = _translations['en'];
    if (enDict != null && enDict.containsKey(key)) {
      return enDict[key]!;
    }
    return key;
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Tally',
      'nav_home': 'Home',
      'nav_insights': 'Insights',
      'nav_goals': 'Goals',
      'nav_accounts': 'Accounts',
      'nav_profile': 'Profile',
      'balance': 'Balance',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'recent_transactions': 'Recent Transactions',
      'see_all': 'See All',
      'add_transaction': 'Add Transaction',
      'no_transactions_yet': 'No transactions yet. Tap + to begin!',
      'savings_vault': 'Savings Vault',
      'budget_limits': 'Monthly Budgets',
      'uncapped_flex': 'Flex Allocation',
      'set_limit': 'Set Limit',
      'stashed': 'stashed',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'close': 'Close',
      'settings': 'Settings',
      'currency': 'Currency',
      'language': 'Language',
      'notifications': 'Notifications',
      'saved_accounts_title': 'Saved Accounts',
      'saved_accounts_desc': 'Accounts remembered on this device for fast 1-tap login',
      'biometric_enabled': 'Biometrics Ready',
      'google_account': 'Google Account',
      'password_saved': 'Password Protected',
      'tap_to_unlock': 'Tap to Login',
      'remove_account': 'Remove from Device',
      'add_another_account': 'Log In with Another Account',
      'confirm_remove_account': 'Remove this account from device quick login?',
      'offline_warning': 'You are offline. Your changes are saved locally and will sync when reconnected.',
      'offline_google_title': 'Internet Connection Required',
      'offline_google_desc': 'Google Sign-In requires an active internet connection. You can create or use a local account right now, and all your records will automatically sync with Google Cloud when you connect to the internet.',
      'use_local_account': 'Continue with Local Account',
      'sync_conflict_title': 'Sync Conflict Detected',
      'sync_conflict_desc': 'We found existing cloud records and newer local records. Please choose how you would like to proceed.',
      'cloud_data': 'Google Cloud Vault',
      'local_data': 'On-Device Storage',
      'restore_cloud': 'Restore from Cloud',
      'upload_local': 'Upload Device Data',
      'offline_data_loss_warning': '⚠️ Notice: Data will only remain on this device. If you uninstall the app or clear device storage, data will be lost.',
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',
      'sign_in_subtitle': 'Sign in to access your ledger & budget',
      'create_account_subtitle': 'Bind a recovery email & create your secure ledger',
      'email_or_username': 'Email or Username',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'login_button': 'Login to Tally',
      'register_button': 'Create Ledger Account',
      'sign_in_with_google': 'Sign in with Google',
      'need_account': 'Need an account? Register with Email',
      'already_registered': 'Already registered? Login here',
      'or_connect_with': 'OR CONNECT WITH',
      'unlock_with_biometrics': 'Unlock with Screen Lock',
    },
    'es': {
      'app_title': 'Tally',
      'nav_home': 'Inicio',
      'nav_insights': 'Estadísticas',
      'nav_goals': 'Metas',
      'nav_accounts': 'Cuentas',
      'nav_profile': 'Perfil',
      'balance': 'Saldo',
      'total_balance': 'Saldo Total',
      'income': 'Ingresos',
      'expense': 'Gastos',
      'recent_transactions': 'Transacciones Recientes',
      'see_all': 'Ver Todo',
      'add_transaction': 'Agregar Transacción',
      'no_transactions_yet': 'Sin transacciones aún. ¡Toca + para comenzar!',
      'savings_vault': 'Bóveda de Ahorros',
      'budget_limits': 'Presupuestos Mensuales',
      'uncapped_flex': 'Asignación Flexible',
      'set_limit': 'Fijar Límite',
      'stashed': 'guardado',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'close': 'Cerrar',
      'settings': 'Ajustes',
      'currency': 'Moneda',
      'language': 'Idioma',
      'notifications': 'Notificaciones',
      'saved_accounts_title': 'Cuentas Guardadas',
      'saved_accounts_desc': 'Cuentas recordadas en este dispositivo para inicio rápido',
      'biometric_enabled': 'Biometría Lista',
      'google_account': 'Cuenta de Google',
      'password_saved': 'Protegido con Contraseña',
      'tap_to_unlock': 'Toca para Iniciar',
      'remove_account': 'Quitar de este Dispositivo',
      'add_another_account': 'Iniciar con Otra Cuenta',
      'confirm_remove_account': '¿Quitar esta cuenta del inicio rápido?',
      'offline_warning': 'Estás desconectado. Los cambios se guardan localmente y se sincronizarán al reconectar.',
      'offline_google_title': 'Conexión a Internet Requerida',
      'offline_google_desc': 'El inicio de sesión de Google requiere conexión a internet. Puedes crear o usar una cuenta local ahora, y tus datos se sincronizarán con la nube al reconectarte.',
      'use_local_account': 'Continuar con Cuenta Local',
      'sync_conflict_title': 'Conflicto de Sincronización Detectado',
      'sync_conflict_desc': 'Encontramos datos en la nube y registros locales más recientes. Elige cómo deseas proceder.',
      'cloud_data': 'Bóveda en la Nube',
      'local_data': 'Almacenamiento Local',
      'restore_cloud': 'Restaurar de la Nube',
      'upload_local': 'Subir Datos Locales',
      'offline_data_loss_warning': '⚠️ Aviso: Los datos solo permanecerán en este dispositivo. Si desinstalas la app o borras la caché, los datos se perderán.',
      'welcome_back': 'Bienvenido de Nuevo',
      'create_account': 'Crear Cuenta',
      'sign_in_subtitle': 'Inicia sesión para acceder a tu libro y presupuesto',
      'create_account_subtitle': 'Vincula un correo de recuperación y crea tu libro seguro',
      'email_or_username': 'Correo o Nombre de Usuario',
      'password': 'Contraseña',
      'confirm_password': 'Confirmar Contraseña',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'login_button': 'Iniciar Sesión en Tally',
      'register_button': 'Crear Cuenta de Libro',
      'sign_in_with_google': 'Iniciar sesión con Google',
      'need_account': '¿Necesitas una cuenta? Regístrate',
      'already_registered': '¿Ya estás registrado? Inicia sesión',
      'or_connect_with': 'O CONECTAR CON',
      'unlock_with_biometrics': 'Desbloquear con Bloqueo de Pantalla',
    },
    'fr': {
      'app_title': 'Tally',
      'nav_home': 'Accueil',
      'nav_insights': 'Aperçus',
      'nav_goals': 'Objectifs',
      'nav_accounts': 'Comptes',
      'nav_profile': 'Profil',
      'balance': 'Solde',
      'total_balance': 'Solde Total',
      'income': 'Revenus',
      'expense': 'Dépenses',
      'recent_transactions': 'Transactions Récentes',
      'see_all': 'Voir Tout',
      'add_transaction': 'Ajouter une Transaction',
      'no_transactions_yet': 'Aucune transaction pour le moment. Appuyez sur + pour commencer!',
      'savings_vault': 'Coffre d\'Épargne',
      'budget_limits': 'Budgets Mensuels',
      'uncapped_flex': 'Allocation Flexible',
      'set_limit': 'Fixer Limite',
      'stashed': 'épargné',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'close': 'Fermer',
      'settings': 'Paramètres',
      'currency': 'Devise',
      'language': 'Langue',
      'notifications': 'Notifications',
      'saved_accounts_title': 'Comptes Enregistrés',
      'saved_accounts_desc': 'Comptes mémorisés sur cet appareil pour connexion rapide',
      'biometric_enabled': 'Biométrie Prête',
      'google_account': 'Compte Google',
      'password_saved': 'Protégé par Mot de Passe',
      'tap_to_unlock': 'Appuyer pour se connecter',
      'remove_account': 'Supprimer de l\'appareil',
      'add_another_account': 'Se connecter avec un autre compte',
      'confirm_remove_account': 'Supprimer ce compte de l\'historique rapide ?',
      'offline_warning': 'Vous êtes hors ligne. Vos modifications sont enregistrées localement et seront synchronisées à la reconnexion.',
      'offline_google_title': 'Connexion Internet Requise',
      'offline_google_desc': 'La connexion Google nécessite internet. Vous pouvez créer ou utiliser un compte local maintenant, et vos données se synchroniseront automatiquement.',
      'use_local_account': 'Continuer avec un Compte Local',
      'sync_conflict_title': 'Conflit de Synchronisation',
      'sync_conflict_desc': 'Nous avons détecté des données dans le cloud et des données locales plus récentes. Veuillez choisir comment procéder.',
      'cloud_data': 'Coffre Cloud Google',
      'local_data': 'Stockage sur l\'appareil',
      'restore_cloud': 'Restaurer depuis le Cloud',
      'upload_local': 'Téléverser Données Locales',
      'offline_data_loss_warning': '⚠️ Avertissement : Les données resteront uniquement sur cet appareil. Si vous désinstallez l\'application, les données seront perdues.',
      'welcome_back': 'Bon retour',
      'create_account': 'Créer un compte',
      'sign_in_subtitle': 'Connectez-vous pour accéder à vos finances',
      'create_account_subtitle': 'Associez un e-mail de récupération et créez votre grand livre',
      'email_or_username': 'E-mail ou nom d\'utilisateur',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'login_button': 'Se connecter à Tally',
      'register_button': 'Créer un compte de grand livre',
      'sign_in_with_google': 'Se connecter avec Google',
      'need_account': 'Besoin d\'un compte ? Inscrivez-vous',
      'already_registered': 'Déjà inscrit ? Connectez-vous',
      'or_connect_with': 'OU SE CONNECTER AVEC',
      'unlock_with_biometrics': 'Déverrouiller avec l\'écran de verrouillage',
    },
    'de': {
      'app_title': 'Tally',
      'nav_home': 'Start',
      'nav_insights': 'Einblicke',
      'nav_goals': 'Ziele',
      'nav_accounts': 'Konten',
      'nav_profile': 'Profil',
      'balance': 'Kontostand',
      'total_balance': 'Gesamtsaldo',
      'income': 'Einnahmen',
      'expense': 'Ausgaben',
      'recent_transactions': 'Letzte Buchungen',
      'see_all': 'Alle anzeigen',
      'add_transaction': 'Buchung hinzufügen',
      'no_transactions_yet': 'Noch keine Buchungen. Tippen Sie auf +!',
      'savings_vault': 'Spartresor',
      'budget_limits': 'Monatliche Budgets',
      'uncapped_flex': 'Flexible Zuweisung',
      'set_limit': 'Limit setzen',
      'stashed': 'gespart',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'edit': 'Bearbeiten',
      'close': 'Schließen',
      'settings': 'Einstellungen',
      'currency': 'Währung',
      'language': 'Sprache',
      'notifications': 'Benachrichtigungen',
      'saved_accounts_title': 'Gespeicherte Konten',
      'saved_accounts_desc': 'Auf diesem Gerät gespeicherte Konten für schnellen Login',
      'biometric_enabled': 'Biometrie Bereit',
      'google_account': 'Google-Konto',
      'password_saved': 'Passwortgeschützt',
      'tap_to_unlock': 'Zum Anmelden tippen',
      'remove_account': 'Vom Gerät entfernen',
      'add_another_account': 'Mit anderem Konto anmelden',
      'confirm_remove_account': 'Dieses Konto aus der Schnellanmeldung entfernen?',
      'offline_warning': 'Sie sind offline. Änderungen werden lokal gespeichert und bei Wiederverbindung synchronisiert.',
      'offline_google_title': 'Internetverbindung erforderlich',
      'offline_google_desc': 'Google-Login erfordert eine aktive Verbindung. Sie können ein lokales Konto verwenden; Daten werden später synchronisiert.',
      'use_local_account': 'Mit lokalem Konto fortfahren',
      'sync_conflict_title': 'Synchronisationskonflikt',
      'sync_conflict_desc': 'Cloud-Daten und neuere lokale Daten wurden gefunden. Bitte wählen Sie, wie fortgefahren werden soll.',
      'cloud_data': 'Google Cloud-Tresor',
      'local_data': 'Lokaler Speicher',
      'restore_cloud': 'Aus Cloud wiederherstellen',
      'upload_local': 'Lokale Daten hochladen',
      'offline_data_loss_warning': '⚠️ Warnung: Daten verbleiben nur auf diesem Gerät. Bei Deinstallation der App gehen die Daten verloren.',
      'welcome_back': 'Willkommen zurück',
      'create_account': 'Konto erstellen',
      'sign_in_subtitle': 'Melden Sie sich an, um auf Ihr Budget zuzugreifen',
      'create_account_subtitle': 'Wiederherstellungs-E-Mail verknüpfen und Hauptbuch sichern',
      'email_or_username': 'E-Mail oder Benutzername',
      'password': 'Passwort',
      'confirm_password': 'Passwort bestätigen',
      'forgot_password': 'Passwort vergessen?',
      'login_button': 'Bei Tally anmelden',
      'register_button': 'Hauptbuchkonto erstellen',
      'sign_in_with_google': 'Mit Google anmelden',
      'need_account': 'Noch kein Konto? Registrieren',
      'already_registered': 'Bereits registriert? Hier anmelden',
      'or_connect_with': 'ODER VERBINDEN MIT',
      'unlock_with_biometrics': 'Mit Bildschirmsperre entsperren',
    },
    'ur': {
      'app_title': 'ٹیلی',
      'nav_home': 'ہوم',
      'nav_insights': 'تجزیات',
      'nav_goals': 'اہداف',
      'nav_accounts': 'اکاؤنٹس',
      'nav_profile': 'پروفائل',
      'balance': 'بیلنس',
      'total_balance': 'کل بیلنس',
      'income': 'آمدنی',
      'expense': 'اخراجات',
      'recent_transactions': 'حالیہ لین دین',
      'see_all': 'سب دیکھیں',
      'add_transaction': 'لین دین شامل کریں',
      'no_transactions_yet': 'ابھی کوئی لین دین نہیں ہے۔ شروع کرنے کے لیے + دبائیں!',
      'savings_vault': 'بچت والٹ',
      'budget_limits': 'ماہانہ بجٹ',
      'uncapped_flex': 'لچکدار مختص',
      'set_limit': 'حد مقرر کریں',
      'stashed': 'محفوظ',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ کریں',
      'delete': 'حذف کریں',
      'edit': 'ترمیم کریں',
      'close': 'بند کریں',
      'settings': 'ترتیبات',
      'currency': 'کرنسی',
      'language': 'زبان',
      'notifications': 'نوٹیفیکیشنز',
      'saved_accounts_title': 'محفوظ شدہ اکاؤنٹس',
      'saved_accounts_desc': 'تیز رفتار لاگ ان کے لیے اس ڈیوائس پر محفوظ اکاؤنٹس',
      'biometric_enabled': 'بائیو میٹرک فعال',
      'google_account': 'گوگل اکاؤنٹ',
      'password_saved': 'پاس ورڈ محفوظ',
      'tap_to_unlock': 'لاگ ان کرنے کے لیے دبائیں',
      'remove_account': 'ڈیوائس سے ہٹائیں',
      'add_another_account': 'دوسرے اکاؤنٹ سے لاگ ان کریں',
      'confirm_remove_account': 'کیا آپ واقعی اس اکاؤنٹ کو ڈیوائس سے ہٹانا چاہتے ہیں؟',
      'offline_warning': 'آپ آف لائن ہیں۔ تبدیلیاں مقامی طور پر محفوظ ہیں اور دوبارہ رابطہ ہونے پر خودکار مطابقت پذیر ہو جائیں گی۔',
      'offline_google_title': 'انٹرنیٹ کنکشن درکار ہے',
      'offline_google_desc': 'گوگل سائن ان کے لیے انٹرنیٹ ضروری ہے۔ آپ ابھی مقامی اکاؤنٹ بنا سکتے ہیں جو بعد میں گوگل کلاؤڈ کے ساتھ مطابقت پذیر ہو جائے گا۔',
      'use_local_account': 'مقامی اکاؤنٹ کے ساتھ جاری رکھیں',
      'sync_conflict_title': 'مطابقت پذیری کا تنازع',
      'sync_conflict_desc': 'کلاؤڈ اور مقامی ڈیٹا دونوں موجود ہیں۔ براہ کرم منتخب کریں کہ آپ کیسے آگے بڑھنا چاہتے ہیں۔',
      'cloud_data': 'گوگل کلاؤڈ ڈیٹا',
      'local_data': 'مقامی ڈیوائس ڈیٹا',
      'restore_cloud': 'کلاؤڈ سے بحال کریں',
      'upload_local': 'مقامی ڈیٹا اپ لوڈ کریں',
      'offline_data_loss_warning': '⚠️ انتباہ: ڈیٹا صرف اس ڈیوائس پر رہے گا۔ اگر آپ ایپ ان انسٹال کرتے ہیں تو ڈیٹا ضائع ہو جائے گا۔',
      'welcome_back': 'خوش آمدید',
      'create_account': 'اکاؤنٹ بنائیں',
      'sign_in_subtitle': 'اپنے کھاتے اور بجٹ تک رسائی کے لیے لاگ ان کریں',
      'create_account_subtitle': 'ریکوری ای میل جوڑیں اور اپنا محفوظ لیجر بنائیں',
      'email_or_username': 'ای میل یا صارف کا نام',
      'password': 'پاس ورڈ',
      'confirm_password': 'پاس ورڈ کی تصدیق کریں',
      'forgot_password': 'پاس ورڈ بھول گئے؟',
      'login_button': 'ٹیلی میں لاگ ان کریں',
      'register_button': 'لیجر اکاؤنٹ بنائیں',
      'sign_in_with_google': 'گوگل کے ساتھ لاگ ان کریں',
      'need_account': 'اکاؤنٹ کی ضرورت ہے؟ رجسٹر کریں',
      'already_registered': 'پہلے سے رجسٹرڈ ہیں؟ لاگ ان کریں',
      'or_connect_with': 'یا اس کے ساتھ منسلک ہوں',
      'unlock_with_biometrics': 'اسکرین لاک کے ساتھ کھولیں',
    },
    'ar': {
      'app_title': 'تالی',
      'nav_home': 'الرئيسية',
      'nav_insights': 'التحليلات',
      'nav_goals': 'الأهداف',
      'nav_accounts': 'الحسابات',
      'nav_profile': 'الملف الشخصي',
      'balance': 'الرصيد',
      'total_balance': 'إجمالي الرصيد',
      'income': 'الدخل',
      'expense': 'المصروفات',
      'recent_transactions': 'المعاملات الأخيرة',
      'see_all': 'عرض الكل',
      'add_transaction': 'إضافة معاملة',
      'no_transactions_yet': 'لا توجد معاملات بعد. اضغط + للبدء!',
      'savings_vault': 'خزينة الادخار',
      'budget_limits': 'الميزانيات الشهرية',
      'uncapped_flex': 'تخصيص مرن',
      'set_limit': 'تحديد الحد',
      'stashed': 'تم ادخاره',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'close': 'إغلاق',
      'settings': 'الإعدادات',
      'currency': 'العملة',
      'language': 'اللغة',
      'notifications': 'الإشعارات',
      'saved_accounts_title': 'الحسابات المحفوظة',
      'saved_accounts_desc': 'الحسابات المحفوظة على هذا الجهاز لتسجيل الدخول السريع',
      'biometric_enabled': 'القياسات الحيوية جاهزة',
      'google_account': 'حساب Google',
      'password_saved': 'محمي بكلمة مرور',
      'tap_to_unlock': 'اضغط لتسجيل الدخول',
      'remove_account': 'إزالة من الجهاز',
      'add_another_account': 'تسجيل الدخول بحساب آخر',
      'confirm_remove_account': 'هل تريد إزالة هذا الحساب من سجل الجهاز؟',
      'offline_warning': 'أنت غير متصل بالإنترنت. تم حفظ تغييراتك محليًا وستتم مزامنتها عند إعادة الاتصال.',
      'offline_google_title': 'الاتصال بالإنترنت مطلوب',
      'offline_google_desc': 'يتطلب تسجيل الدخول عبر Google اتصالاً نشطًا. يمكنك إنشاء حساب محلي الآن وستتم مزامنته لاحقًا.',
      'use_local_account': 'المتابعة بحساب محلي',
      'sync_conflict_title': 'تم اكتشاف تعارض في المزامنة',
      'sync_conflict_desc': 'تم العثور على بيانات سحابية وبيانات محلية أحدث. يرجى اختيار كيفية المتابعة.',
      'cloud_data': 'بيانات Google Cloud',
      'local_data': 'التخزين المحلي بالجهاز',
      'restore_cloud': 'استعادة من السحابة',
      'upload_local': 'رفع البيانات المحلية',
      'offline_data_loss_warning': '⚠️ تحذير: ستبقى البيانات على هذا الجهاز فقط. في حال إلغاء تثبيت التطبيق، سيتم فقد البيانات.',
      'welcome_back': 'مرحبًا بك مجددًا',
      'create_account': 'إنشاء حساب',
      'sign_in_subtitle': 'سجل الدخول للوصول إلى دفتر الأستاذ والميزانية',
      'create_account_subtitle': 'اربط بريد الاسترداد وأنشئ سجلك الآمن',
      'email_or_username': 'البريد أو اسم المستخدم',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'login_button': 'تسجيل الدخول إلى تالي',
      'register_button': 'إنشاء حساب دفتر الأستاذ',
      'sign_in_with_google': 'تسجيل الدخول باستخدام جوجل',
      'need_account': 'تحتاج حساب؟ سجل بالبريد',
      'already_registered': 'مسجل بالفعل؟ سجل الدخول هنا',
      'or_connect_with': 'أو المتابعة باستخدام',
      'unlock_with_biometrics': 'فتح بقفل الشاشة',
    },
    'hi': {
      'app_title': 'टैली',
      'nav_home': 'होम',
      'nav_insights': 'विश्लेषण',
      'nav_goals': 'लक्ष्य',
      'nav_accounts': 'खाते',
      'nav_profile': 'प्रोफ़ाइल',
      'balance': 'बैलेंस',
      'total_balance': 'कुल बैलेंस',
      'income': 'आय',
      'expense': 'खर्च',
      'recent_transactions': 'हाल के लेन-देन',
      'see_all': 'सभी देखें',
      'add_transaction': 'लेन-देन जोड़ें',
      'no_transactions_yet': 'अभी कोई लेन-देन नहीं है। शुरू करने के लिए + दबाएं!',
      'savings_vault': 'बचत वॉल्ट',
      'budget_limits': 'मासिक बजट',
      'uncapped_flex': 'लचीला आवंटन',
      'set_limit': 'सीमा निर्धारित करें',
      'stashed': 'सहेजा गया',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'close': 'बंद करें',
      'settings': 'सेटिंग्स',
      'currency': 'मुद्रा',
      'language': 'भाषा',
      'notifications': 'सूचनाएं',
      'saved_accounts_title': 'सहेजे गए खाते',
      'saved_accounts_desc': 'तेज़ 1-टैप लॉगिन के लिए इस डिवाइस पर सहेजे गए खाते',
      'biometric_enabled': 'बायोमेट्रिक तैयार',
      'google_account': 'Google खाता',
      'password_saved': 'पासवर्ड सुरक्षित',
      'tap_to_unlock': 'लॉगिन करने के लिए टैप करें',
      'remove_account': 'डिवाइस से हटाएं',
      'add_another_account': 'अन्य खाते से लॉगिन करें',
      'confirm_remove_account': 'क्या आप इस खाते को डिवाइस इतिहास से हटाना चाहते हैं?',
      'offline_warning': 'आप ऑफ़लाइन हैं। आपके परिवर्तन स्थानीय रूप से सहेजे गए हैं और पुनः कनेक्ट होने पर सिंक हो जाएंगे।',
      'offline_google_title': 'इंटरनेट कनेक्शन आवश्यक',
      'offline_google_desc': 'Google लॉगिन के लिए सक्रिय इंटरनेट की आवश्यकता है। आप अभी एक स्थानीय खाता बना सकते हैं, जो इंटरनेट जुड़ने पर सिंक हो जाएगा।',
      'use_local_account': 'स्थानीय खाते के साथ जारी रखें',
      'sync_conflict_title': 'सिंक टकराव का पता चला',
      'sync_conflict_desc': 'क्लाउड रिकॉर्ड और नए स्थानीय रिकॉर्ड मिले हैं। कृपया चुनें कि आप कैसे आगे बढ़ना चाहते हैं।',
      'cloud_data': 'Google क्लाउड डेटा',
      'local_data': 'डिवाइस स्थानीय डेटा',
      'restore_cloud': 'क्लाउड से पुनर्स्थापित करें',
      'upload_local': 'स्थानीय डेटा अपलोड करें',
      'offline_data_loss_warning': '⚠️ चेतावनी: डेटा केवल इस डिवाइस पर रहेगा। ऐप अनइंस्टॉल करने पर डेटा नष्ट हो जाएगा।',
      'welcome_back': 'वापसी पर स्वागत है',
      'create_account': 'खाता बनाएं',
      'sign_in_subtitle': 'अपने बहीखाते और बजट तक पहुंचने के लिए लॉगिन करें',
      'create_account_subtitle': 'रिकवरी ईमेल लिंक करें और सुरक्षित बहीखाता बनाएं',
      'email_or_username': 'ईमेल या उपयोगकर्ता नाम',
      'password': 'पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'forgot_password': 'पासवर्ड भूल गए?',
      'login_button': 'टैली में लॉगिन करें',
      'register_button': 'बहीखाता खाता बनाएं',
      'sign_in_with_google': 'गूगल से लॉगिन करें',
      'need_account': 'खाता चाहिए? ईमेल से पंजीकरण करें',
      'already_registered': 'पहले से पंजीकृत हैं? यहां लॉगिन करें',
      'or_connect_with': 'या इसके साथ जुड़ें',
      'unlock_with_biometrics': 'स्क्रीन लॉक से अनलॉक करें',
    },
  };
}
