// File generated by FlutterFire CLI & configured for Tally.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:shared_preferences/shared_preferences.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _prefFirebaseApiKey = 'tally_firebase_api_key';
  static const String _prefFirebaseAppId = 'tally_firebase_app_id';
  static const String _prefFirebaseProjectId = 'tally_firebase_project_id';
  static const String _prefFirebaseSenderId = 'tally_firebase_messaging_sender_id';
  static const String _prefFirebaseAuthDomain = 'tally_firebase_auth_domain';

  // Configured project constants for tally-b3652
  static String apiKey = 'AIzaSyCW-hZvcyqH3OlEEDnCaD8gCpG_XBtcxxw';
  static String appId = '1:494819662703:android:1eed08eedd66202a07e69a';
  static String messagingSenderId = '494819662703';
  static String projectId = 'tally-b3652';
  static String authDomain = 'tally-b3652.firebaseapp.com';
  static String storageBucket = 'tally-b3652.firebasestorage.app';

  /// Checks if Firebase credentials have been configured
  static bool get isConfigured {
    return apiKey.isNotEmpty && projectId.isNotEmpty;
  }

  /// Initializes credentials from SharedPreferences if saved
  static Future<void> loadSavedConfig() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedApiKey = prefs.getString(_prefFirebaseApiKey);
      final savedProjectId = prefs.getString(_prefFirebaseProjectId);
      final savedAppId = prefs.getString(_prefFirebaseAppId);
      final savedSenderId = prefs.getString(_prefFirebaseSenderId);
      final savedAuthDomain = prefs.getString(_prefFirebaseAuthDomain);

      if (savedApiKey != null && savedApiKey.isNotEmpty) apiKey = savedApiKey;
      if (savedProjectId != null && savedProjectId.isNotEmpty) projectId = savedProjectId;
      if (savedAppId != null && savedAppId.isNotEmpty) appId = savedAppId;
      if (savedSenderId != null && savedSenderId.isNotEmpty) messagingSenderId = savedSenderId;
      if (savedAuthDomain != null && savedAuthDomain.isNotEmpty) authDomain = savedAuthDomain;
    } catch (_) {}
  }

  /// Saves runtime configuration
  static Future<void> saveConfig({
    required String newApiKey,
    required String newProjectId,
    String? newAppId,
    String? newSenderId,
    String? newAuthDomain,
  }) async {
    apiKey = newApiKey.trim();
    projectId = newProjectId.trim();
    if (newAppId != null) appId = newAppId.trim();
    if (newSenderId != null) messagingSenderId = newSenderId.trim();
    if (newAuthDomain != null && newAuthDomain.isNotEmpty) {
      authDomain = newAuthDomain.trim();
    } else {
      authDomain = '$projectId.firebaseapp.com';
    }

    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_prefFirebaseApiKey, apiKey);
      await prefs.setString(_prefFirebaseProjectId, projectId);
      await prefs.setString(_prefFirebaseAppId, appId);
      await prefs.setString(_prefFirebaseSenderId, messagingSenderId);
      await prefs.setString(_prefFirebaseAuthDomain, authDomain);
    } catch (_) {}
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJxPjYaYXjNy03olHGCRZb_fv5fQJ2kU',
    appId: '1:494819662703:web:b8c4d6a048754dfa07e69a',
    messagingSenderId: '494819662703',
    projectId: 'tally-b3652',
    authDomain: 'tally-b3652.firebaseapp.com',
    storageBucket: 'tally-b3652.firebasestorage.app',
    measurementId: 'G-KG5XRV1SG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW-hZvcyqH3OlEEDnCaD8gCpG_XBtcxxw',
    appId: '1:494819662703:android:1eed08eedd66202a07e69a',
    messagingSenderId: '494819662703',
    projectId: 'tally-b3652',
    storageBucket: 'tally-b3652.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzlPRrxUcdNxKDN3LcJSLB0aviOXvZE0E',
    appId: '1:494819662703:ios:7f09b58fb0a29c8b07e69a',
    messagingSenderId: '494819662703',
    projectId: 'tally-b3652',
    storageBucket: 'tally-b3652.firebasestorage.app',
    androidClientId: '494819662703-6d959ckki4hv2hbth3v9qddu4voof4ah.apps.googleusercontent.com',
    iosClientId: '494819662703-clad455qm1459ac7frrq3v1ffa1dtq04.apps.googleusercontent.com',
    iosBundleId: 'com.areeb.balanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzlPRrxUcdNxKDN3LcJSLB0aviOXvZE0E',
    appId: '1:494819662703:ios:7f09b58fb0a29c8b07e69a',
    messagingSenderId: '494819662703',
    projectId: 'tally-b3652',
    storageBucket: 'tally-b3652.firebasestorage.app',
    androidClientId: '494819662703-6d959ckki4hv2hbth3v9qddu4voof4ah.apps.googleusercontent.com',
    iosClientId: '494819662703-clad455qm1459ac7frrq3v1ffa1dtq04.apps.googleusercontent.com',
    iosBundleId: 'com.areeb.balanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdJxPjYaYXjNy03olHGCRZb_fv5fQJ2kU',
    appId: '1:494819662703:web:92d94f9d4fbb185f07e69a',
    messagingSenderId: '494819662703',
    projectId: 'tally-b3652',
    authDomain: 'tally-b3652.firebaseapp.com',
    storageBucket: 'tally-b3652.firebasestorage.app',
    measurementId: 'G-E3ZHNZWT0T',
  );
}
